# -------------------- base -------------------- #
FROM node:22.14.0-alpine@sha256:9bef0ef1e268f60627da9ba7d7605e8831d5b56ad07487d24d1aa386336d1944 AS base
RUN adduser -D svelte
USER svelte
WORKDIR /app

# -------------------- build ------------------- #
FROM base AS build
COPY package*.json .
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run lint
RUN npm run build
